GET http://localhost:3000

###
GET http://localhost:3000/orders

###
GET http://localhost:3000/orders/4b14eb1d-4789-4deb-b21d-a7dae5689668

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "amount": 1000.99
}

###
PATCH http://localhost:3000/orders/b53dab5b-81e2-4bc6-98dd-675aea23b58f
Content-Type: application/json

{
    "amount": 2000.99,
    "status": "approved"
}

###
DELETE http://localhost:3000/orders/b53dab5b-81e2-4bc6-98dd-675aea23b58f