GET http://localhost:3000

###
GET http://localhost:3000/orders

###
GET http://localhost:3000/orders/4b14eb1d-4789-4deb-b21d-a7dae5689668

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "amount": 1000.99,
    "status": "approved"
}

###
PATCH http://localhost:3000/orders/bcc12652-e544-453f-af68-97bf4034de5e
Content-Type: application/json

{
    "amount": 2000.99
}

###
DELETE http://localhost:3000/orders/4e81bdfb-a06d-4619-9ca6-152756f55d4c